[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
iprchain = "CoADrt4GSwVVujxn1HuqKMTYVVyrUqqYLG4obi68EpAh"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# [[test.genesis]]
# address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
# program = "tests/programs/mpl_core.so"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d" #mpl_core
